### ISSUE TITLE
Can we get the username from the poster?

### ISSUE THREAD

**Issue by Argon007** [emhl/newsbridge#4]
Hi,

Good job ! ;-)
I want to use this package in a group chat on Telegram. It's working fine and I can see every message in Discord. But is there a way to post the username from the TG user into Discord so I can follow the conversation in Discord?

Now I get this in Discord:

> Hello, how are you?
> I'm fine thanks.
> How are you?

It would be nice if I could see this:

> Joe: Hello, how are you?
> Michael: I'm fine thanks.
> Michael: How are you?

Thanks for your answer!

**Comment by emhl** [comment]
hello @Argon007,
sry for answering so late, this skript is mainly useful to bridge a telegram channel (not a group) to discord (but not the other way around). if you want to use something to bridge a conversation i would recommend something like [TediCross](https://github.com/TediCross/TediCross) 
though you could easily change code so the name of the webhook is the name of the person that sent the telegram message if you really wan't to. but i probably won't add that to the main branch
