### ISSUE TITLE
For some reason send two messages to the discord instead of just one message

### ISSUE THREAD

**Issue by K4mB** [emhl/newsbridge#5]
![New Issue · emhlnewsbridge - Mozilla Firefox](https://user-images.githubusercontent.com/39205487/138605979-469837c8-1f73-4aa7-b496-fddaa4136f55.jpg)
For some reason send two messages to the discord instead of just one message

Last discord message, right telegram message

There would be some way to add in front of the message "@everyone" so in discord I get a notification

**Comment by emhl** [comment]
@K4mB i suspect that solved your issue
