### ISSUE TITLE
Dev Contact

### ISSUE THREAD

**Issue by Crypteys** [emhl/newsbridge#6]
Dev Contact

**Comment by emhl** [comment]
Hey, what's up? How can I help you?

**Comment by Crypteys** [comment]
you already finalized the program?

**Comment by emhl** [comment]
I currently don't have any features that I want to add to the Skript. if you want to add something you can suggest it and feel free to open a pull request.

**Comment by emhl** [comment]
@Crypteys if you have any more questions feel free to write me. i'm closing this for now
